export const types = {
    FETCH_TMDB_DATA_REQUEST: 'FETCH_TMDB_DATA_REQUEST',
    FETCH_TMDB_DATA_SUCCESS: 'FETCH_TMDB_DATA_SUCCESS',
    FETCH_TMDB_DATA_FAILURE: 'FETCH_TMDB_DATA_FAILURE',

    FETCH_SEARCHED_TMDB_DATA_REQUEST: 'FETCH_SEARCHED_TMDB_DATA_REQUEST',
    FETCH_SEARCHED_TMDB_DATA_SUCCESS: 'FETCH_SEARCHED_TMDB_DATA_SUCCESS',
    FETCH_SEARCHED_TMDB_DATA_FAILURE: 'FETCH_SEARCHED_TMDB_DATA_FAILURE',

    SET_QUERY_REQUEST: 'SET_QUERY_REQUEST',
    SET_QUERY_SUCCESS: 'SET_QUERY_SUCCESS',
    SET_QUERY_FAILURE: 'SET_QUERY_FAILURE',
    
    FETCH_VIDEO_REQUEST: 'FETCH_VIDEO_REQUEST',
    FETCH_VIDEO_SUCCESS: 'FETCH_VIDEO_SUCCESS',
    FETCH_VIDEO_FAILURE: 'FETCH_VIDEO_FAILURE',

    RESET_VIDEO_REQUEST: 'RESET_VIDEO_REQUEST',
    RESET_VIDEO_SUCCESS: 'RESET_VIDEO_SUCCESS',
    RESET_VIDEO_FAILURE: 'RESET_VIDEO_FAILURE',
  }